### ISSUE TITLE
DNS: timeout on resolving address on all requests after hours of operation

### ISSUE THREAD

**Issue by berglh** [logstash-plugins/logstash-filter-dns#51]
After upgrading to 6.7.1 version of logstash, the DNS filter works fine for a while and then suddenly starts timing out continuously, thus slowing down pipeline performance dramatically.

>[2019-04-23T22:27:49,497][WARN ][logstash.filters.dns     ] DNS: timeout on resolving address. {:field=>"[source][host]", :value=>"10.48.91.99"}

### Troubleshooting Steps
- Remove failed & hit caches form config
- Downgraded plugin to 3.0.11
- Returned to previously built Logstash 6.5.1 container

The behaviour continued in the first two steps on LS 6.7.1. The behaviour occured straight away after removing the cache size and ttl settings.

Things seem stable again back at LS 6.5.1.

### Investigation
After leaving a comment on #40, @colinsurprenant replied with the following:

> @berglh Thanks for the followup.
> 
> I believe I found the source of the problem. I will need to validate tomorrow but there seems to be a leak (a request id cache fills up which lead to an infinite loop that is aborted by the timeout) in the new version of the resolver code that was updated starting with 6.7. For now, as you noticed, the only workaround is to downgrade to 6.6 (6.6.2 as of now) and just downgrading the dns filter will not help.

### Environment
I'm using the official Logstash containers.
I'm use a caching-only BIND server to service the requests of Logstash, I've configured the name server at the Docker container level. 
The BIND server is always able to correctly resolve the requests correctly if I test against the IPs or host names detailed in the Logstash warning events.
#### Details
- Version: `Logstash 6.7.1`, `Plugin Version 3.0.12`
- Operating System: `Oracle Enterprise Linux 7.3 (Official Docker Container)`
- Config:
```shell
2-general/400000-ad-smb.conf:      dns {
2-general/400000-ad-smb.conf-        resolve => ["[@metadata][destination][address]"]
2-general/400000-ad-smb.conf-        action => "replace"
2-general/400000-ad-smb.conf-        failed_cache_size => 1000
2-general/400000-ad-smb.conf-        failed_cache_ttl => 60
2-general/400000-ad-smb.conf-        hit_cache_size => 10000
2-general/400000-ad-smb.conf-        hit_cache_ttl => 300
2-general/400000-ad-smb.conf-      }
--
2-general/400000-ad-smb.conf:            dns {
2-general/400000-ad-smb.conf-              reverse => ["[@metadata][ip]"]
2-general/400000-ad-smb.conf-              action => "replace"
2-general/400000-ad-smb.conf-              failed_cache_size => 1000
2-general/400000-ad-smb.conf-              failed_cache_ttl => 60
2-general/400000-ad-smb.conf-              hit_cache_size => 10000
2-general/400000-ad-smb.conf-              hit_cache_ttl => 300
2-general/400000-ad-smb.conf-            }
```

**Comment by colinsurprenant** [comment]
Thanks a lot for investigating and creating the issue @berglh.

To recap, this problem affects all versions starting at and after v6.7, including v7 and the only workaround at this point is to downgrade to latest v6 (6.6.2 as of now). 

This problem is in a library included in logstash core but we should be able to apply a patch from the dns filter plugin, similar to what we did in #45.

**Comment by colinsurprenant** [comment]
@berglh are you using the `nameserver` option of the dns filter by any chance? if so, do you have multiple servers configured?

**Comment by colinsurprenant** [comment]
@berglh 

 if you are not using the `nameserver` option then also verify if you have multiple servers configured in your `/etc/resolv.conf`.

IF the answer is yes to either:
- using the `nameserver` option **with multiple** hosts configured
- not using the `nameserver` option but having multiple servers configured in `/etc/resolv.conf` 

then as a **tentative temporary** workaround you can try to reduce to a **SINGLE** server in either the  `nameserver` option or in your `/etc/resolv.conf` and see if it solves.

**Comment by colinsurprenant** [comment]
I have an incoming fix in #52

**Comment by berglh** [comment]
@colinsurprenant Yes I launch the Docker container with the `--dns` option specified for multiple targets, so the resolver can fall over:
>docker run --dns=10.1.1.1 --dns=1.1.1.1 --dns=1.0.0.1 --name %p reg.devops.our.domain.edu.au/logstash-processor -r --log.level warn -b125`

The net result is that multiple name-servers will be configured in `/etc/resolve.conf` which looks like this:
```
[root@logstash-container /]# cat /etc/resolv.conf 
search ourdomain.edu.au
nameserver 10.1.1.1
nameserver 1.1.1.1
nameserver 1.0.0.1
options timeout:1
```
I'm just pushing the `6.7.1` container tag and I'll try it with a single DNS server specified or the container.

**Comment by berglh** [comment]
@colinsurprenant I have now just the BIND caching name server defined in the Docker container explicitly and it has the single `nameserver` in `resolv.con`. 
```shell
[root@logstash-container /]# cat /etc/resolv.conf 
search ourdomain.edu.au
nameserver 10.1.1.1
options timeout:1
```
I'd just like to add that the filter also seems to timeout on the first few look-ups when the logstash pipeline is first started. I'm running 5 instances of logstash on five separate servers, one out of the five instances had four timeouts, however, these timeouts when manually searched against the one configured server resolve correctly.

I'm not sure on the mechanisms logstash uses to determine all plugins are "ready", of if they have just been "started" per se. It feels like there is some transient condition on start-up where the timeout latency for `resolv.rb` is met, but I wonder if it's general contention in the start-up phase as our logstash instances are pretty big at `3498` lines and a pipeline config that looks like this:

```yaml
- pipeline.id: 1-inputs
  pipeline.workers: 3
  path.config: "/usr/share/logstash/pipelines/1-inputs"
  config.reload.automatic: true
- pipeline.id: 2-general
  pipeline.workers: 2
  path.config: "/usr/share/logstash/pipelines/2-general"
- pipeline.id: 3-ldap
  pipeline.workers: 4
  path.config: "/usr/share/logstash/pipelines/3-ldap"
- pipeline.id: 4-dhcp-dns
  pipeline.workers: 3                               
  path.config: "/usr/share/logstash/pipelines/4-dhcp-dns"
- pipeline.id: 5-radius
  pipeline.workers: 2                               
  path.config: "/usr/share/logstash/pipelines/5-radius"
- pipeline.id: 6-syslog
  pipeline.workers: 4                               
  path.config: "/usr/share/logstash/pipelines/6-syslog"
- pipeline.id: 7-outputs
  pipeline.workers: 15                               
  config.reload.automatic: true
  path.config: "/usr/share/logstash/pipelines/7-outputs"
```
![image](https://user-images.githubusercontent.com/12455338/56773632-5530de00-6802-11e9-967e-49e845b51190.png)
